
services:
  frontend:
    build:
      context: ./Front-End
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: frontend_container

  backend:
    build:
      context: ./Back-End
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    container_name: backend_container
